### ISSUE TITLE
Collection of skills

### ISSUE THREAD

**Issue by Lundwicc** [Bluefissure/MultiHit#5]
Hey, is there anyone who have a collection of skills that you can import or do you have to manually add everything yourself? tried to search for a config file that I can import but can't seem to find one.

**Comment by Bluefissure** [comment]
Hi, this plugin is still under testing/beta phase and because of continuing reports of crashing the game (and I didn't successfully figured out a solution) it's on hold for a while.

Actually if you don't use action vfx mod to change your action animations, only few original in-game actions have the animation which looks like multi-hit (such as Fell Cleave). And because of the [built-in delay in tmb](https://github.com/Bluefissure/MultiHit#6-why-is-the-appearance-time-of-flytext-and-the-delay-i-input-for-my-own-presets-not-consistent) you need to modify the tmb file as well, which make the plugin a little bit hard to use.

In one day I need to:
1. Figure out why it crashes the game under certain circumstances (such as heavy AOEs) and how to resolve.
2. Find out a way to automatically handle the built-in flytext delay in tmb.

After that, I may try to introduce the plugin to the main repo of goatcorp and setup a place for users to share the presets.

BTW, if you know [papachin](https://www.youtube.com/c/papapachin), he's the one that proposed this plugin and he provides the presets together with his modpack. Most of his modpacks are paywalled but there're free trials such as [Nero Trial on XMA](https://www.xivmodarchive.com/modid/74685#info).

**Comment by Lundwicc** [comment]
I understand, I will try to create my own, thanks for the explaination :)
